version: "2"

networks:
  extnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

services:
  xchain:
    image: xuperchain:dev
    networks:
      extnetwork:
        ipv4_address: 172.19.0.2
  prometheus:
    image: prom/prometheus:latest
  grafana:
    image: grafana/grafana
    ports:
    - "9000:3000"

