on: [push, pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        diff -u <(echo -n) <(gofmt -d $(find . -type f -name '*.go' -not -path "./vendor/*")) 
        make && make test
        if command -v docker && docker info; then XDEV_CC_IMAGE=xuper/emcc:1.38.30 make contractsdk; fi
        cd ./core/test && bash -x ci_pipeline.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt

  contract-template-sdk:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Test
      run: |
        go build -o xdev github.com/xuperchain/xuperchain/core/cmd/xdev
        export PATH=${PATH}:`pwd`
        go install github.com/xuperchain/xuperchain/core/cmd/xdev
        make -C core/contractsdk/java build && make -C core/contractsdk/java test