on: [push]

name: Docker Cast
jobs:
  docker_test:
    runs-on: macos-latest
    steps:
      - name: install docker 
        run: |
          brew install --cask docker && brew install docker
      - name: docker version
        run: |
          docker version
