on: [push]

name: Docker Cast
jobs:
  docker_test:
    runs-on: ubuntu-latest
    steps:
      - name: install docker 
        run: |
          brew install --cast docker
      - name: docker version
        run: |
          docker version
