on: [push]

name: Docker Cask
jobs:
  docker_test:
    runs-on: macos-latest
    steps:
      - name: install docker 
        run: |
          brew install --cask --no-quarantine docker &&  brew install docker && sudo open -a docker
      - name: start docker
        run: |
          sudo open -a docker
      - name: docker version
        run: |
          docker version
