on: [push]

name: Docker Cast
jobs:
  docker_test:
    runs-on: ubuntu-latest
    steps:
      - name: install docker 
        run: |
          brew tap phinze/homebrew-cask && brew install brew-cask && brew install --cask docker
      - name: docker version
        run: |
          docker version
